services:
  - type: web
    name: echocast-signaling
    runtime: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node signaling.js
    envVars:
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false
      - key: PORT
        value: 10000
